import {GooglePauseError} from './google-api.mjs';
import {jsonFile,readJson,readText,StoragePauseError,textFile,uploadWithRetry} from './hf-pipeline.mjs';
import {compactBatches,createQuotaRouter} from './quota-control.mjs';
import {detectColumns,parseDelimited,serializeDelimited} from './tabular.mjs';

const required=['PROJECT_ID','RUN_ID','HF_TOKEN','HF_DATASET_REPO','GEMINI_API_KEY'];
for(const key of required)if(!process.env[key])throw new Error(`Missing required secret or variable: ${key}`);
const projectId=process.env.PROJECT_ID;const runId=process.env.RUN_ID;const checkpointPath=`checkpoints/${projectId}/review.json`;const statusPath=`status/${projectId}/review.json`;
const statusFile=(status,extra={})=>jsonFile(statusPath,{runId,status,updatedAt:new Date().toISOString(),...extra});
function parsedObject(payload){const raw=String(payload?.candidates?.[0]?.content?.parts?.[0]?.text||'');const start=raw.indexOf('{');const end=raw.lastIndexOf('}');if(start<0||end<start)throw new Error('Google AI did not return a review object');return JSON.parse(raw.slice(start,end+1))}

async function main(){
  try{
    const manifest=await readJson(`queues/${projectId}/${runId}/manifest.json`);if(!manifest)throw new Error('Coordinator manifest not found');const primaryModel=manifest.model||process.env.GEMINI_MODEL||'gemini-3.6-flash';
    const projects=await readJson('projects.json');const project=projects?.find(item=>item.id===projectId);if(!project)throw new Error(`Project not found: ${projectId}`);
    const source=await readText(`projects/${project.id}/${project.fileName}`);if(source===null)throw new Error('Source file not found');const rows=parseDelimited(source,manifest.delimiter);const columns=detectColumns(rows);const dataRows=rows.slice(1);const translations=new Map();const missingTasks=[];
    const glossary=await readJson(`glossaries/${projectId}.json`);if(!glossary?.fixed||glossary.sourceHash!==manifest.sourceHash){await uploadWithRetry([statusFile('paused',{progress:0,checkedRows:0,totalRows:dataRows.length,pauseReason:'analysis_incomplete',message:'Đang chờ glossary cố định.',pausedAt:new Date().toISOString()})]);return}const categoryByIndex=new Map((glossary.categories||[]).map(item=>[Number(item.id)-1,String(item.category||'story')]));
    for(const task of manifest.tasks){const checkpoint=await readJson(`checkpoints/${projectId}/tasks/${task.id}.json`);if(checkpoint?.sourceHash!==manifest.sourceHash||!checkpoint.complete){missingTasks.push(task.id);continue}for(const item of checkpoint.translations||[])if(String(item.translation||'').trim())translations.set(Number(item.index),String(item.translation));if(task.rowIndexes.some(index=>!translations.has(index)))missingTasks.push(task.id)}
    if(missingTasks.length){await uploadWithRetry([statusFile('paused',{progress:0,checkedRows:0,totalRows:dataRows.length,totalTasks:manifest.totalTasks,missingTasks:missingTasks.slice(0,100),pauseReason:'translation_incomplete',message:`Còn ${missingTasks.length} checkpoint cần dịch. Queue sẽ tự tiếp tục.`,pausedAt:new Date().toISOString()})]);return}
    const extension=manifest.delimiter===','?'csv':'tsv';const manualContent=await readText(`results/${project.id}/final.${extension}`);if(manualContent){const manualRows=parseDelimited(manualContent,manifest.delimiter);const manualColumns=detectColumns(manualRows);manualRows.slice(1).forEach((row,index)=>{if(String(row[manualColumns.target]||'').trim())translations.set(index,String(row[manualColumns.target]))})}
    const stored=await readJson(checkpointPath);const usable=stored?.sourceHash===manifest.sourceHash;const issues=Array.isArray(usable?stored.issues:null)?[...stored.issues]:[];const corrections=new Map((usable?stored.corrections:[]).map(item=>[Number(item.index),String(item.translation||'')]));let checkedRows=Math.min(dataRows.length,Number(usable?stored.checkedRows:0)||0);
    const config=manifest.googleConfig||await readJson('config/google-ai.json')||{model:primaryModel};const router=await createQuotaRouter({config,primary:primaryModel});const remaining=dataRows.slice(checkedRows).map((row,offset)=>{const index=checkedRows+offset;return{id:index+1,index,source:String(row[columns.source]||''),translation:String(translations.get(index)||''),category:categoryByIndex.get(index)||'story'}});const batches=compactBatches(remaining,{tokenBudget:router.batchTokenBudget(),maxRows:router.batchRowLimit(),serialize:item=>`${item.id}\t${item.category}\t${item.source}\t${item.translation}`});
    await uploadWithRetry([statusFile('running',{model:primaryModel,progress:dataRows.length?Math.round(checkedRows/dataRows.length*100):100,checkedRows,totalRows:dataRows.length,issueCount:issues.length,correctionCount:corrections.size,resumed:Boolean(usable)})]);
    for(let batchIndex=0;batchIndex<batches.length;batchIndex+=1){const batch=batches[batchIndex];const compact=batch.map(item=>`${item.id}\t${item.category}\t${item.source.replace(/[\r\n\t]+/g,' ')}\t${item.translation.replace(/[\r\n\t]+/g,' ')}`).join('\n');const joined=batch.map(item=>item.source.toLocaleLowerCase()).join('\n');const relevant=(glossary.terms||[]).filter(term=>term.source&&joined.includes(String(term.source).toLocaleLowerCase())).slice(0,120).map(term=>`${term.source}=${term.target}`).join('; ');const prompt=`Review this compact Vietnamese game localization batch against the fixed glossary. Input TSV is ID, CATEGORY, ENG, VI. Check meaning, placeholders, proper names, terminology, pronouns, tone, and concise menu wording. Return corrections only when necessary.
Fixed glossary: ${relevant||'(no matching fixed terms)'}
Return JSON only as {"issues":[{"id":1,"severity":"critical|warning|note","message":"Vietnamese explanation"}],"corrections":[{"id":1,"vi":"corrected Vietnamese"}]}. No Markdown.

ID\tCATEGORY\tENG\tVI
${compact}`;
      try{const response=await router.generate({prompt,temperature:.05,label:'Google AI final review'});const result=parsedObject(response.payload);if(Array.isArray(result.issues))for(const item of result.issues){const id=Number(item.id??Number(item.index)+1);if(batch.some(row=>row.id===id))issues.push({...item,index:id-1})}if(Array.isArray(result.corrections))for(const item of result.corrections){const id=Number(item.id??Number(item.index)+1);if(batch.some(row=>row.id===id)&&String(item.vi??item.translation??'').trim())corrections.set(id-1,String(item.vi??item.translation))}checkedRows+=batch.length;const updatedAt=new Date().toISOString();const checkpoint={version:3,projectId,runId,model:response.model,sourceHash:manifest.sourceHash,checkedRows,issues,corrections:[...corrections].map(([index,translation])=>({index,translation})),updatedAt};await uploadWithRetry([jsonFile(checkpointPath,checkpoint),...router.files(),statusFile('running',{model:response.model,progress:Math.round(checkedRows/dataRows.length*100),checkedRows,totalRows:dataRows.length,issueCount:issues.length,correctionCount:corrections.size,message:`Đã kiểm tra ${checkedRows}/${dataRows.length} dòng`})])}
      catch(error){const pausedAt=new Date().toISOString();const checkpoint={version:3,projectId,runId,model:error.model||primaryModel,sourceHash:manifest.sourceHash,checkedRows,issues,corrections:[...corrections].map(([index,translation])=>({index,translation})),updatedAt:pausedAt};await uploadWithRetry([jsonFile(checkpointPath,checkpoint),...router.files(),statusFile('paused',{model:error.model||primaryModel,progress:dataRows.length?Math.round(checkedRows/dataRows.length*100):100,checkedRows,totalRows:dataRows.length,issueCount:issues.length,correctionCount:corrections.size,pauseReason:error.reason||'invalid_response',message:error.message,pausedAt}),...(error instanceof GooglePauseError&&error.quota?[jsonFile(`status/${projectId}/quota.json`,{runId,model:error.model||primaryModel,reason:error.reason,quota:error.quota,message:error.message,pausedAt,stage:'review'})]:[])]);return}
    }
    dataRows.forEach((row,index)=>{row[columns.target]=corrections.get(index)||translations.get(index)||''});const output=serializeDelimited(rows,manifest.delimiter);const completedAt=new Date().toISOString();const report={version:3,projectId,runId,model:primaryModel,sourceHash:manifest.sourceHash,checkedRows:dataRows.length,issueCount:issues.length,correctionCount:corrections.size,issues,corrections:[...corrections].map(([index,translation])=>({index,translation})),categories:manifest.categories,completedAt};await uploadWithRetry([textFile(`results/${project.id}/final.${extension}`,output,manifest.delimiter===','?'text/csv':'text/tab-separated-values'),jsonFile(`results/${projectId}/review.json`,report),jsonFile(checkpointPath,{...report,complete:true,updatedAt:completedAt}),...router.files(),statusFile('completed',{progress:100,checkedRows:dataRows.length,totalRows:dataRows.length,issueCount:issues.length,correctionCount:corrections.size,completedAt})]);console.log(`Reviewed ${dataRows.length} rows and applied ${corrections.size} corrections`);
  }catch(error){if(error instanceof StoragePauseError){console.warn(error.message);return}try{await uploadWithRetry([statusFile('failed',{error:error.message,failedAt:new Date().toISOString()})])}catch{}throw error}
}

await main();
