import {checkRepoAccess,deleteFiles,downloadFile,listFiles,uploadFiles} from '@huggingface/hub';

export function send(res,status,data){res.status(status).json(data)}
export function allowMethods(req,res,methods){if(methods.includes(req.method))return true;res.setHeader('Allow',methods.join(', '));send(res,405,{error:'Phương thức không được hỗ trợ'});return false}
export function envState(){return{huggingFace:Boolean(process.env.HF_TOKEN&&process.env.HF_DATASET_REPO),github:Boolean(process.env.GITHUB_TOKEN&&process.env.GITHUB_OWNER&&process.env.GITHUB_REPO),dataset:process.env.HF_DATASET_REPO||null,repository:process.env.GITHUB_OWNER&&process.env.GITHUB_REPO?`${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO}`:null,workflow:process.env.GITHUB_WORKFLOW_FILE||'translate.yml'}}
export function safeId(name){return `${Date.now()}-${name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,48)||'project'}`}
function hfRepo(){return{type:'dataset',name:process.env.HF_DATASET_REPO}}
export async function hfCheck(){if(!envState().huggingFace)throw new Error('Hugging Face chưa được cấu hình trên Vercel');await checkRepoAccess({repo:hfRepo(),accessToken:process.env.HF_TOKEN});return true}
export async function readProjects(){if(!envState().huggingFace)return[];try{const response=await downloadFile({repo:hfRepo(),path:'projects.json',accessToken:process.env.HF_TOKEN});if(!response)return[];return JSON.parse(await response.text())}catch(error){if(String(error).includes('404'))return[];throw error}}
export async function readDatasetJson(path){if(!envState().huggingFace)return null;try{const response=await downloadFile({repo:hfRepo(),path,accessToken:process.env.HF_TOKEN});if(!response)return null;return JSON.parse(await response.text())}catch(error){if(String(error).includes('404'))return null;throw error}}
export async function readDatasetText(path){if(!envState().huggingFace)return null;try{const response=await downloadFile({repo:hfRepo(),path,accessToken:process.env.HF_TOKEN});return response?response.text():null}catch(error){if(String(error).includes('404'))return null;throw error}}
export async function listDatasetFiles(prefix=''){if(!envState().huggingFace)return[];const paths=[];for await(const entry of listFiles({repo:hfRepo(),accessToken:process.env.HF_TOKEN,recursive:true})){if(entry.type==='file'&&entry.path.startsWith(prefix))paths.push(entry.path)}return paths}
export async function saveDatasetFiles(files){if(!envState().huggingFace)throw new Error('Hugging Face chưa được cấu hình trên Vercel');await uploadFiles({repo:hfRepo(),accessToken:process.env.HF_TOKEN,files})}
export async function saveProject(project,file){const projects=await readProjects();projects.unshift(project);const createdAt=new Date().toISOString();const files=[{path:'projects.json',content:new Blob([JSON.stringify(projects,null,2)],{type:'application/json'})},{path:`status/${project.id}/project.json`,content:new Blob([JSON.stringify({status:'created',fileValidated:true,stored:true,createdAt},null,2)],{type:'application/json'})}];if(file?.content)files.push({path:`projects/${project.id}/${file.name}`,content:new Blob([file.content],{type:file.type||'text/tab-separated-values'})});await uploadFiles({repo:hfRepo(),accessToken:process.env.HF_TOKEN,files});return project}
export async function removeProject(projectId){const projects=await readProjects();const project=projects.find(item=>item.id===projectId);if(!project)return null;const prefixes=[`projects/${projectId}/`,`status/${projectId}/`,`results/${projectId}/`,`checkpoints/${projectId}/`];const paths=[];for await(const entry of listFiles({repo:hfRepo(),accessToken:process.env.HF_TOKEN,recursive:true})){if(entry.type==='file'&&prefixes.some(prefix=>entry.path.startsWith(prefix)))paths.push(entry.path)}const remaining=projects.filter(item=>item.id!==projectId);await uploadFiles({repo:hfRepo(),accessToken:process.env.HF_TOKEN,files:[{path:'projects.json',content:new Blob([JSON.stringify(remaining,null,2)],{type:'application/json'})}]});if(paths.length)await deleteFiles({repo:hfRepo(),accessToken:process.env.HF_TOKEN,paths,commitTitle:`Delete localization project ${projectId}`});return{project,deletedFiles:paths.length}}
export async function writeProjectStatus(projectId,name,data){if(!envState().huggingFace)throw new Error('Hugging Face chưa được cấu hình trên Vercel');let lastError;for(let attempt=0;attempt<4;attempt+=1)try{await uploadFiles({repo:hfRepo(),accessToken:process.env.HF_TOKEN,files:[{path:`status/${projectId}/${name}.json`,content:new Blob([JSON.stringify(data,null,2)],{type:'application/json'})}]});return data}catch(error){lastError=error;await new Promise(resolve=>setTimeout(resolve,250*(attempt+1)))}throw lastError}
export async function readProjectStatus(projectId,name){return readDatasetJson(`status/${projectId}/${name}.json`)}
export async function github(path,options={}){const state=envState();if(!state.github)throw new Error('GitHub Actions chưa được cấu hình trên Vercel');const response=await fetch(`https://api.github.com/repos/${process.env.GITHUB_OWNER}/${process.env.GITHUB_REPO}${path}`,{...options,headers:{Accept:'application/vnd.github+json',Authorization:`Bearer ${process.env.GITHUB_TOKEN}`,'X-GitHub-Api-Version':'2026-03-10','Content-Type':'application/json',...(options.headers||{})}});if(!response.ok){const body=await response.text();if(response.status===403&&body.includes('Resource not accessible by personal access token'))throw new Error('Token GitHub chưa có quyền Actions: Read and write cho repository này. Hãy cập nhật quyền token trên GitHub rồi lưu lại GITHUB_TOKEN trong Vercel.');throw new Error(`GitHub trả về ${response.status}: ${body.slice(0,240)}`)}return response.status===204?null:response.json()}
